export const SET_CURRENT_PAGE_HASH = 'SET_CURRENT_PAGE_HASH'
export const FETCH_YIKATONG_DATA = 'FETCH_YIKATONG_DATA'
export const SET_YIKATONG_DATA = 'SET_YIKATONG_DATA'
export const SET_YIKATONG_AREAS = 'SET_YIKATONG_AREAS'